
# Version 2013-02-20 

PATH=$PATH:$HOME/bin:/usr/local/bin

ORACLE_SID=`cat /etc/oratab | grep -v ^# | grep ":Y" | tail -1 | cut -d":" -f1` > /dev/null
if [ ! ${ORACLE_SID:-999} = 999 ]
then
        ORAENV_ASK=NO
        . oraenv
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}/lib
        ORAENV_ASK=YES
fi

export PS1="[\u@\h \W] ("\$\{ORACLE_SID\}") \$ "

